# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('contract_type', models.CharField(choices=[('ELT', 'EliteVR'), ('STD', 'StandardVR'), ('RVS', 'RevenueShare'), ('OTR', 'Other')], default=None, max_length=3, null=True)),
                ('date_signed', models.DateField(default=None, null=True)),
                ('date_listed', models.DateField(default=None, null=True)),
                ('commission', models.IntegerField(default=None, null=True)),
                ('billing_type', models.CharField(choices=[('LEG', 'Legacy'), ('BLL', 'Billed'), ('COM', 'Company'), ('OTR', 'Other')], default=None, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.OwnerUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='owners.Owner'),
        ),
    ]
