# Generated by Django 2.0.9 on 2019-08-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'permissions': (('view_owner', 'Can view owners'),)},
        ),
    ]
