# Generated by Django 2.0.9 on 2019-09-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190901_1934'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='coupon_external_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='fee',
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'base')], null=True),
        ),
    ]
