# Generated by Django 2.0.9 on 2019-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0003_auto_20190911_0105")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.PositiveSmallIntegerField(
                choices=[(1337, "free"), (1, "base")], null=True
            ),
        )
    ]
