# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Inquiry'), (1, 'Agreement signed'), (2, 'Agreement rejected'), (3, 'Agreement sent'), (4, 'Quote sent'), (5, 'Reservation created'), (6, 'Reservation modified'), (7, 'Reservation cancelled'), (8, 'Reservation cancellation request'), (9, 'Notes changed'), (10, 'Message received'), (11, 'Message sent'), (12, 'Welcome letter sent'), (13, 'Reminder sent'), (20, 'Payment'), (21, 'Refund'), (22, 'Dispute')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='events_even_timesta_f18d0e_idx'),
        ),
    ]
