# Generated by Django 2.0.9 on 2019-09-04 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Inquiry'), (1, 'Agreement signed'), (2, 'Agreement rejected'), (3, 'Agreement sent'), (4, 'Quote sent'), (5, 'Reservation created'), (6, 'Reservation modified'), (7, 'Reservation cancelled'), (8, 'Reservation cancellation request'), (9, 'Notes changed'), (10, 'Message received'), (11, 'Message sent'), (12, 'Welcome letter sent'), (13, 'Remindecccccr sent'), (20, 'Payment'), (21, 'Refund'), (22, 'Dispute'), (30, 'Model created'), (31, 'Model modified'), (32, 'Model deleted')]),
        ),
    ]
