# Generated by Django 2.0.9 on 2019-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190904_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Inquiry'), (1, 'Agreement signed'), (2, 'Agreement rejected'), (3, 'Agreement sent'), (4, 'Quote sent'), (5, 'Reservation created'), (6, 'Reservation modified'), (7, 'Reservation cancelled'), (8, 'Reservation cancellation request'), (9, 'Notes changed'), (10, 'Message received'), (11, 'Message sent'), (12, 'Welcome letter sent'), (13, 'Reminder sent'), (20, 'Payment'), (21, 'Refund'), (22, 'Dispute'), (30, 'Model created'), (31, 'Model modified'), (32, 'Model deleted')]),
        ),
    ]
