# This configuration file is for our python code formatting tool: Black
# https://github.com/ambv/black

[tool.black]
line-length = 99
exclude = '''
/(
      migrations
    | settings_*\.py
    | manage\.py
    | \.tox
    | \.git
    | dist
    | scripts
)/
'''