# Generated by Django 2.0.9 on 2019-03-07 23:49

import cozmo.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import send_mail.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.FileField(upload_to=cozmo.storages.UploadImageTo('mail/attachments'))),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('thread_id', models.CharField(blank=True, default='', max_length=250)),
                ('unread', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.Reservation')),
            ],
            options={
                'ordering': ('date_updated',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('recipient_info', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('html_text', models.TextField(default='')),
                ('outgoing', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'email'), (2, 'email_managed'), (3, 'sms'), (4, 'phone'), (5, 'api')], null=True)),
                ('external_id', models.CharField(default=None, max_length=128, null=True)),
                ('external_date_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('external_date_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('subject', models.TextField(blank=True, default='')),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'not_started'), (2, 'started'), (3, 'delivered'), (4, 'not_delivered'), (5, 'failed')], default=send_mail.choices.DeliveryStatus(1))),
                ('date_delivered', models.DateTimeField(default=None, null=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='send_mail.Conversation')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.Contact')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.Message'),
        ),
        migrations.CreateModel(
            name='APIMessage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('send_mail.message',),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('send_mail.message',),
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('send_mail.message',),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_created'], name='send_mail_m_convers_f2755a_idx'),
        ),
    ]
