# Generated by Django 2.0.9 on 2019-04-17 23:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='support@voyajoy.com', max_length=128),
            preserve_default=False,
        ),
    ]
