# Generated by Django 2.0.9 on 2019-08-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_auto_20190417_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('date_updated',), 'permissions': (('view_conversation', 'Can view conversation'),)},
        ),
    ]
