# Generated by Django 2.0.9 on 2019-08-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_auto_20190829_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('view_message', 'Can view messages'),)},
        ),
    ]
