# Generated by Django 2.0.9 on 2019-10-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import send_mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190925_2258'),
        ('send_mail', '0004_auto_20190829_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=send_mail.models.generate_name, max_length=255, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_emails', to='accounts.Organization')),
            ],
        ),
    ]
