# Generated by Django 2.0.9 on 2019-10-02 10:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import send_mail.choices


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_forwardingemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseEmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'init'), (2, 'started'), (3, 'pending'), (4, 'completed'), (5, 'error')], default=send_mail.choices.Status(1))),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
