# Generated by Django 2.0.9 on 2019-10-02 21:26

import cozmo.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0006_parseemailtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseEmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.FileField(upload_to=cozmo.storages.UploadImageTo('parse/emails/attachments'))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.ParseEmailTask')),
            ],
        ),
    ]
