# Generated by Django 2.0.9 on 2019-10-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0007_parseemailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseemailattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='send_mail.ParseEmailTask'),
        ),
    ]
