# Generated by Django 2.0.9 on 2019-10-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0008_auto_20191002_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardingemail',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
