# Generated by Django 2.0.9 on 2019-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0009_forwardingemail_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='automated',
            field=models.BooleanField(default=False),
        ),
    ]
