# Generated by Django 2.0.9 on 2019-10-16 20:56

from django.db import migrations, models
import send_mail.choices


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0010_message_automated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_email_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='parseemailtask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'init'), (2, 'started'), (3, 'pending'), (4, 'completed'), (5, 'error'), (6, 'queue')], default=send_mail.choices.Status(1)),
        ),
    ]
