# Generated by Django 2.0.9 on 2019-10-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0011_auto_20191016_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_reference',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
