# Generated by Django 2.0.9 on 2019-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0012_message_reply_to_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseemailtask',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
