# Generated by Django 2.0.9 on 2019-10-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('send_mail', '0013_parseemailtask_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseemailtask',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='parseemailtask',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
