# Generated by Django 2.0.9 on 2019-10-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0014_auto_20191017_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forwardingemail',
            options={'permissions': (('view_forwardingemail', 'Can view forwarding emails'),)},
        ),
    ]
