# Generated by Django 2.0.9 on 2019-07-31 20:59

import cozmo.storages
from django.db import migrations, models
import django.db.models.deletion
import rental_network.models


class Migration(migrations.Migration):

    replaces = [('rental_network', '0001_initial'), ('rental_network', '0002_auto_20190516_2107'), ('rental_network', '0003_auto_20190516_2349'), ('rental_network', '0004_auto_20190621_0030'), ('rental_network', '0005_auto_20190705_2240'), ('rental_network', '0006_auto_20190705_2342'), ('rental_network', '0007_auto_20190706_0216'), ('rental_network', '0008_listing'), ('rental_network', '0009_auto_20190712_0142'), ('rental_network', '0010_listing_account'), ('rental_network', '0011_account_organization'), ('rental_network', '0012_longtermrentalsettings'), ('rental_network', '0013_auto_20190723_0047'), ('rental_network', '0014_auto_20190723_0203')]

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0007_auto_20190627_2338'),
        ('listings', '0008_auto_20190723_0037'),
        ('listings', '0005_auto_20190509_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'ZILLOW')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('host', models.URLField()),
                ('port', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.Account')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.Proxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalNetworkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'INIT'), (2, 'STARTED'), (3, 'PAUSED'), (4, 'ERROR'), (5, 'STOPPED'), (6, 'COMPLETED'), (7, 'CANCELLED')], default=1)),
                ('step', models.CharField(max_length=36)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.Account')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.Proxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.RentalNetworkJob')),
                ('image', models.ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('selenium/images'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_preference',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EMAIL'), (2, 'PHONE'), (3, 'EMAIL PHONE')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ZILLOW'), (2, 'APARTMENTS')]),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='account',
            name='last_verification_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='two_factor_phone',
            field=models.CharField(default=4153018572, max_length=16),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'INIT'), (2, 'UPLOADING'), (3, 'UPDATING'), (4, 'SUBMITTED'), (5, 'LIVE'), (6, 'ERROR'), (7, 'DELISTED'), (8, 'DELETED')], default=rental_network.models.Listing.Status(1))),
                ('listing_type', models.PositiveSmallIntegerField(choices=[(1, 'ZILLOW'), (2, 'APARTMENTS')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_network.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rentalnetworkjob',
            name='job_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREATE'), (2, 'UPDATE'), (3, 'DELETE')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalnetworkjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'INIT'), (1, 'STARTED'), (2, 'PAUSED'), (3, 'ERROR'), (4, 'STOPPED'), (5, 'COMPLETED'), (6, 'CANCELLED')], default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Organization'),
        ),
        migrations.CreateModel(
            name='LongTermRentalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('lease_duration', models.IntegerField(default=None, null=True)),
                ('date_available', models.DateField(default=None, null=True)),
                ('lease_terms', models.TextField(blank=True, default='')),
                ('prop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_rental_settings', to='listings.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rentalnetworkjob',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_network_jobs', to='listings.Property'),
        ),
    ]
