# Generated by Django 2.0.9 on 2019-08-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0001_initial_squashed_0014_auto_20190723_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_network.Account'),
        ),
    ]
