# Generated by Django 2.0.9 on 2019-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
