# Generated by Django 2.0.9 on 2019-05-16 23:49

import cozmo.storages
from django.db import migrations
import rental_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0002_auto_20190516_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='url',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='image',
            field=rental_network.models.Base64ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('selenium/images')),
        ),
    ]
