# Generated by Django 2.0.9 on 2019-06-21 00:30

import cozmo.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0003_auto_20190516_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('selenium/images')),
        ),
    ]
