# Generated by Django 2.0.9 on 2019-07-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0004_auto_20190621_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contact_name',
            new_name='contact_first_name',
        ),
        migrations.AddField(
            model_name='account',
            name='contact_last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contact_preference',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EMAIL'), (2, 'PHONE'), (3, 'EMAIL PHONE')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ZILLOW'), (2, 'APARTMENTS')]),
        ),
    ]
