# Generated by Django 2.0.9 on 2019-07-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0006_auto_20190705_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_verification_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='two_factor_phone',
            field=models.CharField(default=4153018572, max_length=16),
            preserve_default=False,
        ),
    ]
