# Generated by Django 2.0.9 on 2019-07-10 23:28

from django.db import migrations, models
import django.db.models.deletion
import rental_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0007_auto_20190627_2338'),
        ('rental_network', '0007_auto_20190706_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'INIT'), (2, 'UPLOADING'), (3, 'UPDATING'), (4, 'SUBMITTED'), (5, 'LIVE'), (6, 'ERROR'), (7, 'DELISTED'), (8, 'DELETED')], default=rental_network.models.Listing.Status(1))),
                ('listing_type', models.PositiveSmallIntegerField(choices=[(1, 'ZILLOW'), (2, 'APARTMENTS')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
