# Generated by Django 2.0.9 on 2019-07-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0008_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalnetworkjob',
            name='job_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREATE'), (2, 'UPDATE'), (3, 'DELETE')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalnetworkjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'INIT'), (1, 'STARTED'), (2, 'PAUSED'), (3, 'ERROR'), (4, 'STOPPED'), (5, 'COMPLETED'), (6, 'CANCELLED')], default=0),
        ),
    ]
