# Generated by Django 2.0.9 on 2019-07-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0009_auto_20190712_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_network.Account'),
            preserve_default=False,
        ),
    ]
