# Generated by Django 2.0.9 on 2019-07-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0012_longtermrentalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermrentalsettings',
            name='lease_duration',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='longtermrentalsettings',
            name='lease_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
