# Generated by Django 2.0.9 on 2019-07-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_network', '0013_auto_20190723_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalnetworkjob',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_network_jobs', to='listings.Property'),
        ),
    ]
