# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('listings', '0001_initial'),
        ('owners', '0001_initial'),
        ('rental_connections', '0001_initial'),
        ('crm', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='payments.PlaidTransaction'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Contact'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='rate',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='arrival_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.ArrivalInstruction'),
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Building'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='listings.Feature'),
        ),
        migrations.AddField(
            model_name='property',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Group'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Location'),
        ),
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='owners.Owner'),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='listings.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_connections.RentalConnection'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='prop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Coordinates'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_set', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='listingdescriptions',
            name='prop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='image',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='houserules',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='feature',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='discount',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='booking_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_out', to='listings.BookingSettings'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='prop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='blocking',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='prop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_amenities', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='availabilitysettings',
            name='prop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='availability',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='additionalfee',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('listings.additionalfee',),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('listings.additionalfee',),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['name'], name='listings_fe_name_f7ca25_brin'),
        ),
    ]
