# Generated by Django 2.0.9 on 2019-03-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190307_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfee',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservationfee',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='additionalfee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservationfee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
