# Generated by Django 2.0.9 on 2019-04-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190320_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='time_zone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
