# Generated by Django 2.0.9 on 2019-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190509_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='base_total',
            field=models.DecimalField(decimal_places=2, help_text='Total base price', max_digits=12, null=True),
        )
    ]
