# Generated by Django 2.0.9 on 2019-07-23 00:37

from django.db import migrations, models
import listings.choices


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190627_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicamenities',
            name='free_parking',
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='cats_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='dogs_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='gated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='hardwood_flooring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='large_dogs_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='laundry_type',
            field=models.CharField(blank=True, choices=[('SHD', 'shared'), ('INU', 'in unit'), ('COP', 'coin op'), ('NON', 'none')], default=listings.choices.LaundryType('NON'), max_length=3),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='parking_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='parking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('GRG', 'garage'), ('SRF', 'surface lot'), ('CVD', 'covered'), ('OTH', 'other'), ('NON', 'none')], default=listings.choices.ParkingType('NON'), max_length=3),
        ),
    ]
