# Generated by Django 2.0.9 on 2019-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190723_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicamenities',
            name='free_parking',
            field=models.BooleanField(default=False),
        ),
    ]
