# Generated by Django 2.0.9 on 2019-08-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_basicamenities_free_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicamenities',
            name='wifi_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='basicamenities',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
