# Generated by Django 2.0.9 on 2019-08-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190813_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'App'), (2, 'Web'), (3, 'Airbnb'), (4, 'VRBO'), (5, 'Booking'), (6, 'Tripadvisor'), (7, 'Recommended')], default=1),
        ),
    ]
