# Generated by Django 2.0.9 on 2019-08-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190814_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='smart_pricing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
