# Generated by Django 2.0.9 on 2019-08-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190817_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='smart',
            field=models.BooleanField(default=False),
        ),
    ]
