# Generated by Django 2.0.9 on 2019-08-27 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0013_auto_20190819_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('group_access', 'Can access group'),)},
        ),
        migrations.AddField(
            model_name='groupuserassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_assignments', to='listings.Group'),
        ),
        migrations.AddField(
            model_name='groupuserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
