# Generated by Django 2.0.9 on 2019-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190827_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': (('public_api_access', 'Can access data in Public API'), ('view_property', 'Can view property')), 'verbose_name_plural': 'properties'},
        ),
    ]
