# Generated by Django 2.0.9 on 2019-08-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20190828_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('view_reservation', 'Can view reservations'),)},
        ),
    ]
