# Generated by Django 2.0.9 on 2019-08-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190828_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('group_access', 'Can access group'), ('view_group', 'Can view groups'))},
        ),
    ]
