# Generated by Django 2.0.9 on 2019-08-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20190829_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationnote',
            options={'permissions': (('view_reservationnote', 'Can view reservation notes'),)},
        ),
    ]
