# Generated by Django 2.0.9 on 2019-09-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20190925_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'renter'), (2, 'dates'), (3, 'payment'), (4, 'fraud')], default=None, null=True),
        ),
    ]
