# Generated by Django 2.0.9 on 2019-10-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_externallisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
    ]
