# Generated by Django 2.0.9 on 2019-10-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20191002_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total Price', max_digits=12, null=True),
        ),
    ]
