# Generated by Django 2.0.9 on 2019-10-15 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20191003_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='listings.Reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
