# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rental_integrations.choices
import rental_integrations.trip_advisor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripAdvisorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('session', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, 'pending'), (1, 'installed')], default=rental_integrations.trip_advisor.models.TripAdvisorStatus(0))),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripAdvisorSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('auto_push_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'listed'), (2, 'unlisted'), (3, 'blocked'), (4, 'pending'), (5, 'init'), (6, 'failed publish')], default=rental_integrations.choices.ListingStatus(5))),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'not ready'), (3, 'ready for review'), (4, 'approved'), (5, 'rejected')], default=rental_integrations.choices.ListingApprovalStatus(2))),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'sync all'), (2, 'sync rates and availability'), (3, 'sync undecided')], default=rental_integrations.choices.ListingSyncScope(3))),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_advisor.TripAdvisorAccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tripadvisor_sync', to='listings.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_advisor.TripAdvisorAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='tripadvisoraccount',
            unique_together={('user_id', 'organization')},
        ),
    ]
