# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cozmocalendar',
            name='prop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cozmo_calendar', to='listings.Property'),
        ),
        migrations.AddIndex(
            model_name='externalcalendarevent',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['uid'], name='calendars_e_uid_eec6fc_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendarevent',
            unique_together={('uid', 'external_cal')},
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendar',
            unique_together={('name', 'cozmo_cal')},
        ),
    ]
