# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_schedule', models.SmallIntegerField(blank=True, choices=[(0, 'at booking'), (1, 'at check in'), (101, 'days before 1'), (107, 'days before 7'), (114, 'days before 14'), (160, 'days before 60'), (190, 'days before 90')], default=None, null=True)),
                ('payment_template', models.SmallIntegerField(blank=True, choices=[(1, 'payment 100'), (2, 'payment 50 50'), (3, 'payment 33 33 34')], default=None, null=True)),
                ('payment_custom_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('properties', models.IntegerField()),
                ('cancellation_policy', models.CharField(blank=True, choices=[('EA', 'Full'), ('OK', 'Relaxed'), ('FA', 'Flexible'), ('RI', 'Moderate'), ('FI', 'Firm'), ('ST', 'Strict'), ('SS', 'Super Strict'), ('LT', 'Long Term'), ('NR', 'No Refunds'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('month_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(31)])),
                ('trip_advisor_sync', models.BooleanField(default=False)),
                ('booking_sync', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
        ),
    ]
