features_map = {
    "Air Conditioning": "AIR_CONDITIONING",
    "Balcony": "BALCONY_OR_TERRACE",
    # '': 'BEACHFRONT',
    # '': 'BEACH_OR_LAKESIDE_RELAXATION',
    "Bicycles": "BICYCLES_AVAILABLE",
    "Boating": "BOAT_AVAILABLE",
    "TV - Cable": "CABLE_SATELLITE_TV",
    "TV - Satellite": "CABLE_SATELLITE_TV",
    # '': 'CEILING_FANS',
    "Heating": "CENTRAL_HEATING",
    # '': 'CHILDRENS_POOL',
    # '': 'CITY_GETAWAY',
    "Cycling": "CYCLING_TRIPS",
    "Dishwasher": "DISHWASHER",
    "Hair Dryer": "DRYER",
    "DVD Player": "DVD_PLAYER",
    "Elevators": "ELEVATOR_IN_BUILDING",
    "Fireplace": "FIREPLACE",
    "Fishing": "FISHING_NEARBY",
    "Freezer": "FREEZER",
    # '': 'GAMES_ROOM',
    "Golf": "GOLF_NEARBY (1)",
    # '': 'GOLF_WITHIN_DRIVE (2)',
    "Grill/BBQ - Grill": "GRILL",
    # '': 'GYM',
    "Pool - Shared": "HEATED_OUTDOOR_POOL_SHARED",
    "Pool - Private": "HEATED_OUTDOOR_POOL_PRIVATE",
    "Hiking": "HIKING_TRIPS",
    "Horseback Riding": "HORSE_RIDING_NEARBY",
    "Housekeeping": "HOUSEKEEPING_INCLUDED",
    # '': 'INDOOR_POOL_SHARED',
    "Pool - Indoor": "INDOOR_POOL_PRIVATE",
    # '': 'INTERNET_ACCESS',
    "Iron": "IRON",
    "Jacuzzi": "JACUZZI_OR_HOT_TUB",
    "Electric Kettle": "KETTLE",
    # '': 'LINENS_PROVIDED',
    "Microwave": "MICROWAVE",
    "Mountain View": "MOUNTAIN_VIEWS",
    # '': 'OCEAN_VIEWS',
    "Patio": "PATIO",
    "Ping Pong": "PING_PONG_TABLE",
    "Pool Table": "POOL_TABLE",
    "Fenced Yard": "PRIVATE_YARD",
    "Parking": "PARKING_SPACE",
    # '': 'REFRIGERATOR',
    # '': 'RURAL_COUNTRYSIDE_RETREATS',
    "Sauna": "SAUNA",
    "Skiing": "SKIING (3)",
    # '': 'STAFFED_PROPERTY',
    # '': 'STEREO_SYSTEM',
    # '': 'SAFE',
    "Stove": "STOVE",
    # '': 'SUNROOF_OR_ROOF_TERRACE',
    "Tennis": "TENNIS_COURTS_NEARBY",
    # '': 'TRAMPOLINE',
    "Toaster": "TOASTER",
    "Towels": "TOWELS_PROVIDED",
    "Tv": "TV",
    # '': 'UNHEATED_OUTDOOR_POOL_SHARED',
    # '': 'UNHEATED_OUTDOOR_POOL_PRIVATE',
    # '': 'WASHING_MACHINE',
    # '': 'WATERFRONT',
    # '': 'WATERSPORTS_NEARBY',
    # '': 'WATER_VIEWS',
    "Internet/Wifi": "WIFI",
}

prop_type_map = {
    "Apartment": "APARTMENT",
    "Bed and Breakfast": "B_AND_B",
    "Barn": "BARN",
    "Beach Hut": "BEACH_HUT",
    "Boat": "BOATHOUSE",
    "Bungalow": "BUNGALOW",
    "Camper Rv": "CAMPER_VAN",
    "Caravan Mobile Home": "CARAVAN_MOBILE_HOME",
    "Castle": "CASTLE",
    "Cave": "CAVE_HOUSE",
    "Chalet": "CHALET",
    "Chateau": "CHATEAU",
    "Condo": "CONDO",
    "Converted_Chapel": "CONVERTED_CHAPEL",
    "Cottage": "COTTAGE",
    "Farmhouse": "FARMHOUSE",
    "Finca": "FINCA",
    "Fort": "FORT",
    "Gite": "GITE",
    "Guesthouse": "GUEST_HOUSE",
    "Hotel": "HOTEL_APARTMENT",
    "House": "HOUSE",
    # '', 'HOUSEBOAT', #BOATHOUSE ?!?!?
    "Light House": "LIGHT_HOUSE",
    "Lodge": "LODGE",
    "Cabin": "LOG_CABIN",
    "Manor House": "MANOR_HOUSE",
    "Narrow Boat": "NARROWBOAT",
    "Pent House": "PENT_HOUSE",
    "Room": "ROOM (1)",
    "Riad": "RIAD",
    "Shepherds Hut": "SHEPHERDS_HUT",
    "Ski Chalet": "SKI_CHALET",
    "Studio": "STUDIO (2)",
    "Tented Camp": "TENTED_CAMP",
    "Tipi": "TIPI_TEEPEE",
    "Tower": "TOWER",
    "Townhouse": "TOWNHOUSE",
    "Treehouse": "TREE_HOUSE",
    "Trullo": "TRULLO",
    "Villa": "VILLA",
    "Watermill": "WATERMILL",
    "Windmill": "WINDMILL",
    "Yacht": "YACHT",
    "Yurt": "YURT",
}

revert_prop_type_map = {**{v: k for k, v in prop_type_map.items()}, "HOUSEBOAT": "Boat"}
