# Generated by Django 2.0.9 on 2019-05-09 01:18

import chat.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('early_bag_dropoff_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('discount_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('refund_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('early_check_in_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('thanks_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('distance_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('recommendations_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('amenities_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('wifi_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('availability_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('late_check_out_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('location_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('cancellation_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
                ('pets_enabled', models.PositiveIntegerField(choices=[(1, 'DISABLED'), (2, 'AUTO ALWAYS'), (3, 'ASK ALWAYS'), (4, 'NO ALWAYS')], default=chat.choices.ChatSetting(1))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
