# Generated by Django 2.0.9 on 2019-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'owner'), (2, 'admin'), (3, 'contributor'), (4, 'developer'), (5, 'contractor'), (6, 'analyst')], default=3, max_length=2),
            preserve_default=False,
        ),
    ]
