# Generated by Django 2.0.9 on 2019-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'owner'), (2, 'admin'), (3, 'contributor'), (4, 'contributor group'), (5, 'developer'), (6, 'contractor'), (7, 'analyst')], max_length=2),
        ),
    ]
