# Generated by Django 2.0.9 on 2019-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190829_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'contributor'), (4, 'contributor group'), (5, 'cleaner'), (6, 'developer'), (7, 'contractor'), (8, 'analyst')]),
        ),
    ]
