# Generated by Django 2.0.9 on 2019-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190829_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'contributor'), (4, 'contributor group'), (5, 'cleaner'), (6, 'property owner'), (7, 'developer'), (8, 'contractor'), (9, 'analyst')]),
        ),
    ]
