# Generated by Django 2.0.9 on 2019-09-01 19:34

import accounts.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190901_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'contributor'), (4, 'contributor group'), (5, 'cleaner'), (6, 'property owner'), (7, 'developer'), (8, 'contractor'), (9, 'analyst')], default=accounts.choices.RoleTypes(2), null=True),
        ),
    ]
