# Generated by Django 2.0.9 on 2019-09-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190901_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
