# Generated by Django 2.0.9 on 2019-09-25 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190911_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='applications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(1, 'iCal Magic'), (2, 'Reservation'), (3, 'Owners'), (4, 'Vendors')]), blank=True, default=list, size=None),
        ),
    ]
