# Generated by Django 2.0.9 on 2019-10-16 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190925_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='applications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(1, 'iCal Magic'), (2, 'Reservation'), (3, 'Owners'), (4, 'Vendors'), (5, 'Messages')]), blank=True, default=list, size=None),
        ),
    ]
