from listings.choices import PropertyTypes

features_map = {
    "24-Hour Check-In": None,
    "Access": None,
    "Adventure": None,
    "Air Conditioning": "Air Conditioning",
    "Antiquing": None,
    "Arboretum": None,
    "Atm/Bank": "ATM Bank",
    "Autumn Foliage": None,
    "Away From It All": None,
    "Babysitter": None,
    "Balcony": "Balcony",
    "Basketball Court": None,
    "Bathroom 1": None,
    "Bathroom 2": None,
    "Bathroom 3": None,
    "Bathroom 4": None,
    "Bathroom 5": None,
    "Bathroom 6": None,
    "Bathroom 7": None,
    "Bathrooms": None,
    "Bathtub": None,
    "Bay/Sound": None,
    "Beachcombing": None,
    "Bed Linens": None,
    "Bedding 1": None,
    "Bedding 10": None,
    "Bedding 2": None,
    "Bedding 3": None,
    "Bedding 4": None,
    "Bedding 5": None,
    "Bedding 6": None,
    "Bedding 7": None,
    "Beds": None,
    "Bicycles": "Bicycles",
    "Bird Watching": None,
    "Boat": None,
    "Boating": "Boating",
    "Bonus Room": None,
    "Books": None,
    "Botanical Garden": None,
    "Breakfast": "Breakfast",
    "Budget": None,
    "Building Name": None,
    "Buzzer/Wireless Intercom": None,
    "Cable": "TV - Cable",
    "Cable Tv": "TV - Cable",
    "Carbon Monoxide Detector": "Carbon Monoxide Detector",
    "Cat(S)": None,
    "Catering Available": None,
    "Caves": None,
    "Chauffeur": None,
    "Children Welcome": "Children Friendly",
    "Churches": "Churches",
    "Cinemas": "Cinemas",
    "Cleaning Before Checkout": None,
    "Clothes Dryer": "Laundry - Dryer",
    "Coffee Maker": "Coffee Maker",
    "Coin Laundry": "Laundry - Dryer - Coin-op",
    "Communal Pool": "Pool - Shared",
    "Community Pool": "Pool - Shared",
    "Complex": "Complex",
    "Complex Type": "Complex",
    "Concierge": None,
    "Conference Room": "onference Room",
    "Cooking Basics": None,
    "Cooking Range": None,
    "Cross Country Skiing": "Cross Country Skiing",
    "Cycling": "Cycling",
    "Deck": "Deck",
    "Deck / Patio": None,
    "Deck Or Balcony": "Balcony",
    "Deepsea Fishing": None,
    "Den": None,
    "Dining Area": None,
    "Dining Room": None,
    "Dishes & Utensils": None,
    "Dishes And Silverware": None,
    "Dishwasher": "Dishwasher",
    "Distance To Ski Lift": None,
    "Distance To Town": None,
    "Dog(S)": None,
    "Doorman": None,
    "Downtown": None,
    "Dry Sauna": None,
    "Dryer": "Hair Dryer",
    "Duty Free Shops": None,
    "Dvd": "DVD Player",
    "Dvd Player": "DVD Player",
    "Dvd Players": "DVD Player",
    "E-Lock": None,
    "Eco Tourism": None,
    "Elevator": "Elevators",
    "Equestrian Events": None,
    "Essentials": None,
    "Events Allowed": "Events Friendly",
    "Exercise Room": None,
    "Extra Bedding": None,
    "Extra Bedding 2": None,
    "Extra Pillows And Blankets": None,
    "Extra Room": None,
    "Family": None,
    "Family/Kid Friendly": "Children Friendly",
    "Fax": "Fax",
    "Festivals": None,
    "Fire Extinguisher": "Fire Extinguisher",
    "Fireplace": "Fireplace",
    "Firm Mattress": None,
    "First Aid Kit": "First Aid Kit",
    "Fishing": "Fishing",
    "Fitness Center": "Fitness Center",
    "Fitness Room / Equipment": None,
    "Flat Screen Tv'S": None,
    "Fly Fishing": None,
    "Foosball": "Foosball",
    "Forests": None,
    "Free Parking On Premises": None,
    "Free Shuttle": None,
    "Free Wifi": None,
    "Freshwater Fishing": None,
    "Full Kitchen": None,
    "Gambling Casinos": None,
    "Game Room": None,
    "Games": None,
    "Garage": "Parking - Garage",
    "Garden Or Backyard": None,
    "Gas Grill / Bbq": None,
    "Golf": "Golf",
    "Golf Course View": None,
    "Golf Nearby": None,
    "Grill/Bbq": "Grill/BBQ - Grill",
    "Groceries": None,
    "Grouping": None,
    "Guests Provide Their Own Meals": None,
    "Gym": None,
    "Hair Dryer": "Hair Dryer",
    "Handicap": None,
    "Handicap Accessible": None,
    "Hangers": None,
    "Health/Beauty Spa": "Spa",
    "Heated Pool": None,
    "Heater": None,
    "Heating": "Heating",
    "High Speed Internet": None,
    "Hiking": "Hiking",
    "Historic": None,
    "Horseback Riding": "Horseback Riding",
    "Horseshoes": None,
    "Hospital": None,
    "Hot Air Ballooning": "Hot Air Ballooning",
    "Hot Tub": "Hot Tub",
    "Hot Water": None,
    "Housekeeper Included": None,
    "Housekeeper Optional": None,
    "Housekeeping": "Housekeeping",
    "Hunting": None,
    "Hunting Big Game": None,
    "Hunting Small Game": None,
    "Ice Skating": "Ice Skating",
    "Indoor Fireplace": "Fireplace",
    "Indoor Pool": None,
    "Internet": "Internet/Wifi",
    "Internet Access": "Internet/Wifi",
    "Iron": "Iron",
    "Iron & Board": None,
    "Jacuzzi": "Jacuzzi",
    "Jet Skiing": "Jet Skiing",
    "Kayak / Canoe": None,
    "Kayaking": "Kayaking",
    "Keypad": None,
    "Kitchen": None,
    "Kitchenette": None,
    "Lake View": None,
    "Laptop Friendly Workspace": None,
    "Laundromat": "Laundromat",
    "Laundry": None,
    "Lawn / Garden": None,
    "Library": None,
    "Linens Provided": None,
    "Live Theater": None,
    "Living Room": None,
    "Lock On Bedroom Door": None,
    "Lockbox": None,
    "Loft": None,
    "Long Term Stays Allowed": None,
    "Long-Term Renters Welcome": None,
    "Luaus": None,
    "Luggage Dropoff Allowed": None,
    "Marina": None,
    "Massage": "Massage",
    "Massage Therapist": None,
    "Medical Services": None,
    "Microwave": "Microwave",
    "Miniature Golf": "Miniature Golf",
    "Minimum Age Limit For Renters": None,
    "Monument View": None,
    "More 3": None,
    "More1": None,
    "Mountain Biking": "Mountain Biking",
    "Mountain Climbing": "Mountain Climbing",
    "Mountain View": "Mountain View",
    "Mountaineering": "Mountaineering",
    "Museums": "Museums",
    "Necessary": None,
    "No Smoking": None,
    "No Telephone": None,
    "Non Smoking Only": None,
    "Not Necessary": None,
    "Nude Beach": None,
    "On Golf Course": None,
    "Other Pet(S)": None,
    "Outdoor Grill": "Grill/BBQ - Outdoor",
    "Outlet Shopping": None,
    "Outside Shower": None,
    "Oven": "Oven",
    "Pace": None,
    "Paddle Boating": None,
    "Pantry Items": None,
    "Paragliding": "Paragliding",
    "Parking": "Parking",
    "Parking Spaces": None,
    "Parking Type": None,
    "Pets": None,
    "Pets Allowed": "Pets Friendly",
    "Pets Considered": None,
    "Pets Live On This Property": None,
    "Pets Not Allowed": None,
    "Pets Permitted": "Pets Friendly",
    "Photography": None,
    "Pier Fishing": None,
    "Ping Pong Table": "Ping Pong",
    "Playground": "Playground",
    "Pond": None,
    "Pool": "Pool",
    "Pool Access": None,
    "Pool Table": "Pool Table",
    "Pri Hot Tub": None,
    "Private Chef": None,
    "Private Entrance": None,
    "Private Hot Tub": None,
    "Private Living Room": None,
    "Private Pool": "Pool - Private",
    "Racquetball": "Racquetball",
    "Rafting": "Rafting",
    "Rain Forests": None,
    "Rating": None,
    "Recommended": None,
    "Recreation Center": "Recreation Center",
    "Refrigerator": None,
    "Resort": "Resort",
    "Restaurants": None,
    "Rock Climbing": "Rock Climbing",
    "Roller Blading": "Roller Blading",
    "Romantic": None,
    "Ruins": None,
    "Rural": None,
    "Safety Card": None,
    "Sailing": None,
    "Satellite / Cable": None,
    "Sauna": "Sauna",
    "Scenic Drives": None,
    "Self Check-In": None,
    "Shampoo": "Shampoo",
    "Shelling": None,
    "Shopping": None,
    "Shuffleboard": "Shuffleboard",
    "Shuttle Service": None,
    "Sight Seeing": None,
    "Single Story": None,
    "Ski & Snowboard": None,
    "Ski Access": None,
    "Ski In - Ski Out": None,
    "Ski Lift Privileges": None,
    "Ski Privileges Optional": None,
    "Ski Storage": None,
    "Ski-In": None,
    "Ski-In / Ski-Out": None,
    "Ski-Out": None,
    "Skiing": "Skiing",
    "Sledding": "Sledding",
    "Smoke Detector": "Smoke Detector",
    "Snorkeling": "Snorkeling",
    "Snorkeling/Diving": None,
    "Snowboarding": "Snowboarding",
    "Snowmobiling": "Snowmobiling",
    "Spa": "Spa",
    "Spa/Jacuzzi": "Spa",
    "Sports & Activities": None,
    "Sports Groups": None,
    "Staff": None,
    "Stereo": None,
    "Stories": None,
    "Stove": "Stove",
    "Suitable For Children": "Children Friendly",
    "Suitable For Events": "Events Friendly",
    "Summer Rentals": None,
    "Surfing": "Surfing",
    "Swimming": None,
    "Synagogues": "Synagogues",
    "Telephone": None,
    "Television": "TV",
    "Tennis": "Tennis",
    "Toaster": "Toaster",
    "Tourist Attractions": None,
    "Towels Provided": "Towels",
    "Town Shuttle": None,
    "Tv": "TV",
    "Tv'S": "TV",
    "Vcr": None,
    "Video Games": None,
    "Video Library": None,
    "View": None,
    "Village": None,
    "Volcano": None,
    "Walking": None,
    "Washer": "Laundry - Washer",
    "Washer Dryer": "Laundry - Dryer",
    "Washing Machine": None,
    "Water Parks": None,
    "Water Skiing": "Water Skiing",
    "Water Tubing": "Water Tubing",
    "Water View": None,
    "Waterfalls": None,
    "Whale Watching": None,
    "Wheelchair Accessible": "Wheelchair Friendly",
    "Wheelchair Inaccessible": None,
    "Whitewater Rafting": None,
    "Wifi": "Internet/Wifi",
    "Wildlife Viewing": "Wildlife Viewing",
    "Wind-Surfing": None,
    "Winery Tours": "Winery Tours",
    "Wireless Internet": "Internet/Wifi",
    "Wood Stove": None,
}


property_types_map = {
    "Townhome": PropertyTypes.Townhouse.pretty_name,
    "Condo": PropertyTypes.Condo.pretty_name,
    "Duplex": PropertyTypes.Other.pretty_name,
    "Private Home": PropertyTypes.House.pretty_name,
}
