# Generated by Django 2.0.9 on 2019-08-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationsettings',
            options={'permissions': (('view_organizationsettings', 'Can view organization settings'),)},
        ),
    ]
