# Generated by Django 2.0.9 on 2019-03-07 23:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rental_integrations.airbnb.choices
import rental_integrations.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('session', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('image_url', models.URLField(default='', null=True)),
                ('image_url_large', models.URLField(default='', null=True)),
                ('first_name', models.CharField(default='', max_length=64, null=True)),
                ('last_name', models.CharField(default='', max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirbnbSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('auto_push_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'listed'), (2, 'unlisted'), (3, 'blocked'), (4, 'pending'), (5, 'init'), (6, 'failed publish')], default=rental_integrations.choices.ListingStatus(5))),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'not ready'), (3, 'ready for review'), (4, 'approved'), (5, 'rejected')], default=rental_integrations.choices.ListingApprovalStatus(2))),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'sync all'), (2, 'sync rates and availability'), (3, 'sync undecided')], default=rental_integrations.choices.ListingSyncScope(3))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('guest_id', models.IntegerField(default=None, null=True)),
                ('preferred_locale', models.CharField(blank=True, default='', max_length=4)),
                ('phone_numbers', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('confirmation_code', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_guests', models.IntegerField(default=None, null=True)),
                ('guest_id', models.IntegerField(default=None, null=True)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('guest_first_name', models.CharField(blank=True, default='', max_length=64)),
                ('guest_last_name', models.CharField(blank=True, default='', max_length=64)),
                ('guest_preferred_locale', models.CharField(blank=True, default='', max_length=4)),
                ('guest_phone_numbers', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('expected_payout_amount_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_base_price', models.IntegerField(blank=True, default=None, null=True)),
                ('listing_base_price_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_host_fee_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_cancellation_host_fee_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_cancellation_payout_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_security_price_accurate', models.CharField(blank=True, max_length=32)),
                ('occupancy_tax_amount_paid_to_host_accurate', models.CharField(blank=True, max_length=32)),
                ('listing_cleaning_fee_accurate', models.CharField(blank=True, max_length=32)),
                ('transient_occupancy_tax_paid_amount_accurate', models.CharField(blank=True, max_length=32)),
                ('total_paid_amount_accurate', models.CharField(blank=True, max_length=32)),
                ('standard_fees_details', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('transient_occupancy_tax_details', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('thread_id', models.IntegerField(default=None, null=True)),
                ('is_preconfirmed', models.BooleanField(default=False)),
                ('raw_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('status_type', models.CharField(choices=[('new', 'new'), ('accept', 'accept'), ('deny', 'deny'), ('pending', 'pending'), ('timeout', 'timeout'), ('pending_voided', 'pending voided'), ('pending_payment', 'pending payment'), ('cancelled_by_admin', 'cancelled by admin'), ('cancelled_by_host', 'cancelled by host'), ('cancelled_by_guest', 'cancelled by guest'), ('at_checkpoint', 'at checkpoint'), ('checkpoint_voided', 'checkpoint voided')], default=rental_integrations.airbnb.choices.ReservationStatus('new'), max_length=32)),
                ('cancellation_policy_category', models.CharField(choices=[('flexible', 'flexible'), ('moderate', 'moderate'), ('strict', 'strict'), ('strict_14_with_grace_period', 'strict 14 with grace period'), ('super_strict_30', 'super strict 30'), ('super_strict_60', 'super strict 60'), ('long_term', 'long term'), ('long_term_grace_period', 'long term grace period'), ('flexible_new', 'flexible new'), ('moderate_new', 'moderate new'), ('strict_new', 'strict new'), ('strict_14_with_grace_period_new', 'strict 14 with grace period new'), ('super_strict_30_new', 'super strict 30 new'), ('super_strict_60_new', 'super strict 60 new')], default=rental_integrations.airbnb.choices.CancellationPolicy('flexible'), max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationPayoutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_payout_amount', models.IntegerField()),
                ('listing_base_price', models.IntegerField()),
                ('listing_cancellation_host_fee', models.IntegerField()),
                ('listing_cancellation_payout', models.IntegerField()),
                ('listing_host_fee', models.IntegerField()),
                ('occupancy_tax_amount_paid_to_host', models.IntegerField()),
                ('transient_occupancy_tax_paid_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('managed_business_entity_id', models.IntegerField(default=None, null=True)),
                ('phone', models.CharField(default='', max_length=32)),
                ('picture_url', models.URLField(blank=True, default='', null=True)),
                ('picture_url_large', models.URLField(blank=True, default='', null=True)),
                ('airbnb_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_user', to='app_marketplace.AirbnbApp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
