# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('airbnb', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_reservation', to='listings.Reservation'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_photo', to='listings.Image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airbnb.AirbnbAccount'),
        ),
        migrations.AddField(
            model_name='airbnbsync',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airbnb.AirbnbAccount'),
        ),
        migrations.AddField(
            model_name='airbnbsync',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='airbnbsync',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_sync', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='airbnbaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='airbnbaccount',
            unique_together={('user_id', 'organization')},
        ),
    ]
