# Generated by Django 2.0.9 on 2019-03-07 23:49

import cozmo.storages
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.FileField(upload_to=cozmo.storages.UploadImageTo('mail/attachments'))),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, default='')),
                ('text', models.TextField()),
                ('outgoing', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Reservation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('content', models.TextField()),
                ('headline', models.CharField(blank=True, default='', max_length=100)),
                ('template_type', models.CharField(blank=True, choices=[('E', 'Email'), ('M', 'Message')], default='E', max_length=1)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('prop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
                ('tags', models.ManyToManyField(to='message_templates.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters, numbers and underscore are allowed', regex='\\w+')])),
                ('value', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_templates.Mail'),
        ),
        migrations.CreateModel(
            name='WelcomeTemplate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('message_templates.template',),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['reservation', 'date'], name='message_tem_reserva_10d083_idx'),
        ),
    ]
