# Generated by Django 2.0.9 on 2019-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttemplate',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
