# Generated by Django 2.0.9 on 2019-08-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0002_auto_20190618_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'permissions': (('view_template', 'Can view templates'),)},
        ),
    ]
