# Generated by Django 2.0.9 on 2019-09-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0003_auto_20190829_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
    ]
