# Generated by Django 2.0.9 on 2019-03-07 23:49

import cozmo.storages
import cozmo_common.db.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', cozmo_common.db.fields.PhoneField(blank=True, max_length=16)),
                ('secondary_phone', cozmo_common.db.fields.PhoneField(blank=True, max_length=16)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('crm/guests'))),
                ('location', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('external_id', models.CharField(default='', max_length=150)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('summary', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.SmallIntegerField(choices=[(1, 'Question'), (2, 'Incident'), (3, 'Problem'), (4, 'Task')])),
                ('priority', models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('status', models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Pending'), (2, 'Solved')], default=0)),
                ('source', models.SmallIntegerField(choices=[(0, 'Manual'), (1, 'Email')], default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Organization')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.SmallIntegerField(choices=[(1, 'Link'), (2, 'Duplicate')], default=1)),
                ('from_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crm.Ticket')),
                ('to_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_by', to='crm.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.Ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-date_created', '-priority'], name='crm_ticket_date_cr_c8dfcc_idx'),
        ),
    ]
