# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('listings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsync',
            name='prop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='listings.Property'),
        ),
        migrations.AddField(
            model_name='bookingaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingaccount',
            unique_together={('user_id', 'organization')},
        ),
    ]
