# Generated by Django 2.0.9 on 2019-03-07 23:49

import cozmo.storages
import datetime
from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('vendors/tasks'))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('CSV', 'Service'), ('CRT', 'Reimbursement'), ('CSP', 'Supplies'), ('CRF', 'Refund'), ('CMS', 'Misc'), ('COT', 'Other')], default='COT', max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('disbursed', models.BooleanField(default=False)),
                ('date_disbursed', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='vendors.ChecklistItem')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('time_frame', django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True)),
                ('time_estimate', models.DurationField(blank=True, default=datetime.timedelta(0, 3600))),
                ('job_type', models.CharField(choices=[('JCU', 'Checkup'), ('JCL', 'Clean'), ('JDE', 'Delivery'), ('JGR', 'Greet'), ('JRE', 'Repair')], max_length=3)),
                ('status', models.CharField(blank=True, choices=[('SNA', 'Not Accepted'), ('SAS', 'Not Accepted Seen'), ('SNS', 'Accepted'), ('SIN', 'Incomplete'), ('SIP', 'In Progress'), ('SPA', 'Paused'), ('SCO', 'Completed'), ('SUN', 'Unable To Complete'), ('SCA', 'Cancelled'), ('SDC', 'Declined')], default='SNA', max_length=3)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('entry_instructions', models.TextField(blank=True, default='', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cozmo.storages.UploadImageTo('vendors/report'))),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_problem', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_set', to='vendors.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_preference', models.CharField(blank=True, choices=[('E', 'Email'), ('S', 'SMS')], default='E', max_length=3)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('payout_preference', models.SmallIntegerField(choices=[(0, 'Check'), (1, 'ACH'), (2, 'Cash')])),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_properties', models.ManyToManyField(blank=True, through='vendors.Assignment', to='listings.Property')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'Accept'), (2, 'Decline'), (3, 'Start'), (4, 'Pause'), (5, 'Stop'), (6, 'Finish'), (7, 'Contact'), (8, 'Problem'), (9, 'Cancel'), (10, 'Init'), (11, 'Seen'), (12, 'Incomplete'), (13, 'Finish Unable'), (14, 'Reassign'), (20, 'Arrive'), (21, 'Leaves')])),
                ('on_premise', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_set', to='vendors.Job')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='job',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property'),
        ),
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_set', to='vendors.Job'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='vendors.Job'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('vendor', 'prop')},
        ),
    ]
