# Generated by Django 2.0.9 on 2019-08-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20190829_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('view_job', 'Can view jobs'),)},
        ),
    ]
