# Generated by Django 2.0.9 on 2019-08-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20190829_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': (('view_assignment', 'Can view assignments'),)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('view_report', 'Can view reports'),)},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ('date_created',), 'permissions': (('view_worklog', 'Can view work logs'),)},
        ),
    ]
