# Generated by Django 2.0.9 on 2019-08-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20190829_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('view_job', 'Can view jobs'), ('change_job_status', 'Can change job status'))},
        ),
    ]
