# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import message_templates.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAutomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('days_delta', models.SmallIntegerField()),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'BOOKING'), (2, 'CANCELLATION'), (3, 'CHECK_IN'), (4, 'CHECK_OUT'), (5, 'MESSAGE'), (6, 'CHANGE')])),
                ('time', models.TimeField()),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'EMAIL'), (2, 'SMS'), (3, 'MESSAGE'), (4, 'AUTO')], default=message_templates.choices.TransportMethod(4))),
                ('recipient', models.PositiveSmallIntegerField(choices=[(1, 'GUEST'), (2, 'OWNER'), (3, 'OTHER')], default=message_templates.choices.Recipient(1))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'BOOKING'), (2, 'CANCELLATION'), (3, 'CHECK_IN'), (4, 'CHECK_OUT'), (5, 'MESSAGE'), (6, 'CHANGE')])),
                ('content', models.TextField(blank=True, default='')),
                ('subject', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
