# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('message_templates', '0001_initial'),
        ('automation', '0001_initial'),
        ('send_mail', '0001_initial'),
        ('crm', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='send_mail.Message'),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.Contact'),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_emails', to='listings.Reservation'),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.ReservationAutomation'),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='message_templates.Template'),
        ),
    ]
