# Generated by Django 2.0.9 on 2019-04-17 23:25

import automation.choices
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20190307_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationautomation',
            name='recipient',
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='cc_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='recipient_address',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reservationautomation',
            name='recipient_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'guest'), (2, 'email')], default=automation.choices.RecipientType(1)),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='recipient_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='reservationmessage',
            name='recipient',
            field=models.CharField(default='', max_length=128),
        ),
    ]
