# Generated by Django 2.0.9 on 2019-04-19 00:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20190417_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationautomation',
            name='bcc_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
