# Generated by Django 2.0.9 on 2019-08-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_reservationautomation_bcc_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationautomation',
            options={'permissions': (('view_reservationautomation', 'Can view reservation automations'),)},
        ),
    ]
