# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('api_type', models.CharField(choices=[('ISI', 'Isi'), ('ESC', 'Escapia')], max_length=3)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.SmallIntegerField(choices=[(0, 'Enabled'), (1, 'Disabled'), (2, 'Hidden')], default=0)),
                ('auto_correct', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('client_id', models.CharField(blank=True, default='', max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('features', models.ManyToManyField(blank=True, to='listings.Feature')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'permissions': (('public_api_access', 'Can access data in Public API'),),
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Synced'), (1, 'Syncing'), (2, 'Error')])),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('rental_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rental_connections.RentalConnection')),
            ],
        ),
    ]
