# Generated by Django 2.0.9 on 2019-08-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalconnection',
            options={'permissions': (('public_api_access', 'Can access data in Public API'), ('view_rentalconnection', 'Can view rental connections'))},
        ),
    ]
