# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YelpCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
