# Generated by Django 2.0.9 on 2019-03-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('msisdn', models.CharField(max_length=16, unique=True)),
                ('country_code', models.CharField(default='', max_length=2)),
                ('source', models.CharField(default='', max_length=16)),
                ('capabilities', models.CharField(default='', max_length=32)),
                ('number_type', models.CharField(default='', max_length=16)),
                ('active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
