# Generated by Django 2.0.9 on 2019-03-16 00:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
